# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Shuo Zhang
first_name: Shuo
middle_name:
last_name: Zhang
chinese_name: 张硕
email: "sz_whu@163.com"
description: "A junior student in Wuhan University"
position: "Junior Student"
affiliation: "Wuhan University"
college: "Hongyi Honor College"
show_avatar: false
copyright_year: "2024"
# The URL of your site
url: "https://shuozhang.dev"
baseurl: ""

# GitHub Pages settings
github:
  repository_name: shuozhang.dev
  repository_url: https://github.com/shuozhang196/shuozhang.dev

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub Pages settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# -----------------------------------------------------------------------------
# Layout settings
# -----------------------------------------------------------------------------
max_width: 1200px
# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: shuozhang196
google_scholar: ""
linkedin_username: ""
twitter_username: ""
# -----------------------------------------------------------------------------
# Additional links
# -----------------------------------------------------------------------------
lab_website: ""
lab_name: ""
conference_website: ""
conference_name: ""
software_page: false
school_website: ""
ssrn: ""
# -----------------------------------------------------------------------------
# Analytics
# -----------------------------------------------------------------------------
google_analytics: ""